language: r
warnings_are_errors: false
sudo: required
cache: packages

notifications:
  email:
    recipients:
      - nicolas.casajus@gmail.com

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
