# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: required
cache: packages

notifications:
  email:
    recipients:
      - nicolas.casajus@gmail.com
